databases:
  - name: t4tdatabase
    plan: free
    databaseName: t4tdatabase
    user: otter234

services:
  - type: web
    plan: free
    name: t4tweb
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn TeaTime_engine.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: t4tdatabase
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4